### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by kirtr** [nsg/snap-springlobby#7]
It looks like there is a new version of the Lobby and the SpringRTS engine. Any chance of updating the snap? Thank you!

**Comment by nsg** [comment]
Hi, sorry for the slow response. It was a little tricky to get everything to build, the build instructions for Ubuntu is not the best so there was a little guesswork from my part. I have now published version 0.270 of the snap.

It's a somewhat large release, this is one of my older snaps that I started with back in early 2017 and a lot of things have changed in the snap ecosystem since then, so I had to do quite a lot of refactoring. I hope there is no regressions and everything still works.

I have played a little under Ubuntu 20.04 with no problems.

From now on (if nothing breaks) the edge channel should always contain an automatic build of the latest lobby. With this it should in theory be easy for me to keep it up to date. Time will tell! :)

**Comment by kirtr** [comment]
Nice! I'll give it a go. Thank you for your efforts to make it easy to use on Linux!
